//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorServiceConsumer.CalculatorService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CalculatorService.CalculatorServiceSoap")]
    public interface CalculatorServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Addition", ReplyAction="*")]
        decimal Addition(decimal numberOne, decimal numberTwo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Addition", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> AdditionAsync(decimal numberOne, decimal numberTwo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Substraction", ReplyAction="*")]
        decimal Substraction(decimal numberOne, decimal numberTwo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Substraction", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> SubstractionAsync(decimal numberOne, decimal numberTwo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Multiplication", ReplyAction="*")]
        decimal Multiplication(decimal numberOne, decimal numberTwo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Multiplication", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> MultiplicationAsync(decimal numberOne, decimal numberTwo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Division", ReplyAction="*")]
        decimal Division(decimal numberOne, decimal numberTwo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Division", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> DivisionAsync(decimal numberOne, decimal numberTwo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalculatorServiceSoapChannel : CalculatorServiceConsumer.CalculatorService.CalculatorServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculatorServiceSoapClient : System.ServiceModel.ClientBase<CalculatorServiceConsumer.CalculatorService.CalculatorServiceSoap>, CalculatorServiceConsumer.CalculatorService.CalculatorServiceSoap {
        
        public CalculatorServiceSoapClient() {
        }
        
        public CalculatorServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculatorServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public decimal Addition(decimal numberOne, decimal numberTwo) {
            return base.Channel.Addition(numberOne, numberTwo);
        }
        
        public System.Threading.Tasks.Task<decimal> AdditionAsync(decimal numberOne, decimal numberTwo) {
            return base.Channel.AdditionAsync(numberOne, numberTwo);
        }
        
        public decimal Substraction(decimal numberOne, decimal numberTwo) {
            return base.Channel.Substraction(numberOne, numberTwo);
        }
        
        public System.Threading.Tasks.Task<decimal> SubstractionAsync(decimal numberOne, decimal numberTwo) {
            return base.Channel.SubstractionAsync(numberOne, numberTwo);
        }
        
        public decimal Multiplication(decimal numberOne, decimal numberTwo) {
            return base.Channel.Multiplication(numberOne, numberTwo);
        }
        
        public System.Threading.Tasks.Task<decimal> MultiplicationAsync(decimal numberOne, decimal numberTwo) {
            return base.Channel.MultiplicationAsync(numberOne, numberTwo);
        }
        
        public decimal Division(decimal numberOne, decimal numberTwo) {
            return base.Channel.Division(numberOne, numberTwo);
        }
        
        public System.Threading.Tasks.Task<decimal> DivisionAsync(decimal numberOne, decimal numberTwo) {
            return base.Channel.DivisionAsync(numberOne, numberTwo);
        }
    }
}
